# -*- coding: utf-8 -*-
"""Entrega2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cVTLTrTV9dm1iVuXCLtMDzpmdVQjWNcs

# Etapa 1 – Pré-processamento dos Dados

*   Organizar os datasets de imagens e dados temporais coletados na Sprint 1.
*   Realizar tratamento dos dados, garantindo que estejam estruturados e prontos para serem usados no modelo.
*   Identificar padrões e sazonalidades na série temporal NDVI, explorando diferentes abordagens estatísticas para entender variações de produtividade.
"""

# Importar as bibliotecas
import os
from google.colab import files
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import tensorflow as tf


# Verificar Google Colab
try:
    import google.colab
    IN_COLAB = True
    print("Executando no Google Colab")
except:
    IN_COLAB = False
    print("Executando localmente")

# Configurações gerais
plt.style.use('seaborn-v0_8')
sns.set(style="whitegrid")
np.random.seed(42)
tf.random.set_seed(42)

# Criar diretórios para salvar resultados
def criar_diretorios():
    """
    Cria os diretórios necessários para armazenar os dados processados e resultados.
    """
    diretorios = [
        'dados_originais',
        'dados_processados',
        'resultados',
        'resultados/modelos',
        'resultados/graficos',
        'resultados/metricas'
    ]

    for diretorio in diretorios:
        os.makedirs(diretorio, exist_ok=True)
        print(f"Diretório '{diretorio}' criado ou já existente.")

# Chamar a função para criar diretórios
criar_diretorios()

"""# Dados SatVeg

Dados obtidos do sensor SatVeg para a Fazenda São José, Sorriso-MT
Coordenadas: -55.95520,-12.88229 | -55.95729,-12.88229
"""

# Bibliotecas necessárias
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.seasonal import seasonal_decompose
import numpy as np

# Upload do arquivo
print("1. Carregamento dos dados do SatVeg")
from google.colab import files
uploaded = files.upload()

# Carregar o arquivo CSV
filename = list(uploaded.keys())[0]
df_satveg = pd.read_csv(filename, encoding='latin1', sep=';')

# Salvar os dados originais no diretório apropriado
original_path = os.path.join('dados_originais', 'satveg_original.csv')
df_satveg.to_csv(original_path, index=False)
print(f"Dados originais salvos em: {original_path}")

# Informações básicas
print(f"Arquivo carregado: {filename}")
print(f"Dimensões: {df_satveg.shape[0]} linhas x {df_satveg.shape[1]} colunas")

# Pré-processamento
print("\n Pré-processamento dos dados")

# Converter colunas data
if 'Data' in df_satveg.columns:
    df_satveg['Data'] = pd.to_datetime(df_satveg['Data'], format='%d/%m/%Y', errors='coerce')
    print("- Coluna 'Data' convertida para datetime")

# Criando colunas auxiliares
df_satveg['mes'] = df_satveg['Data'].dt.month
df_satveg['ano'] = df_satveg['Data'].dt.year

# Converter colunas numéricas
colunas_numericas = ["NDVI", "PreFiltro", "FlatBottom"]
print("- Convertendo colunas numéricas:")

for coluna in colunas_numericas:
    if coluna in df_satveg.columns:
        # Guardar tipo original para mostrar a mudança
        tipo_original = df_satveg[coluna].dtype

        # Converter de string com vírgula para float
        if df_satveg[coluna].dtype == 'object':
            df_satveg[coluna] = df_satveg[coluna].str.replace(',', '.').astype(float)
            print(f"  Coluna '{coluna}' convertida: {tipo_original} → {df_satveg[coluna].dtype}")
        else:
            print(f"  Coluna '{coluna}' já é do tipo numérico: {df_satveg[coluna].dtype}")
    else:
        print(f"  Atenção: Coluna '{coluna}' não encontrada no DataFrame")

# Verificar valores nulos
nulos = df_satveg.isnull().sum()
print("- Valores nulos por coluna:")
print(nulos[nulos > 0] if any(nulos > 0) else "  Não há valores nulos")

df_satveg.head()

# Garante que 'Data' está como datetime
df_satveg['Data'] = pd.to_datetime(df_satveg['Data'], errors='coerce')

# Cria a coluna 'AnoMes' no formato 'YYYY-MM'
df_satveg['AnoMes'] = df_satveg['Data'].dt.to_period('M').astype(str)

if 'NDVI' in df_satveg.columns and 'AnoMes' in df_satveg.columns:
    # Para cada mês, calcula a média e atribui a todas as linhas daquele mês
    df_satveg['NDVI_media_mensal'] = df_satveg.groupby('AnoMes')['NDVI'].transform('mean')
    print("\nColuna 'NDVI_media_mensal' adicionada ao DataFrame!")
    print(df_satveg[['Data', 'NDVI', 'AnoMes', 'NDVI_media_mensal']].head())
else:
    print("\nNão foi possível criar a média mensal do NDVI: Colunas necessárias não encontradas.")

# Análise Exploratória Básica
print("\n Análise Exploratória Básica")
print("- Primeiras linhas dos dados:")
display(df_satveg.head())

print("\n- Resumo estatístico das colunas numéricas:")
display(df_satveg[colunas_numericas].describe())

# Visualização de Dados
print("\n Visualização de Dados")

# 4.1 Distribuições (histogramas)
print(" Histograma - Distribuição das variáveis:")
plt.figure(figsize=(15, 5))

for i, coluna in enumerate(colunas_numericas):
    plt.subplot(1, 3, i+1)
    sns.histplot(df_satveg[coluna], kde=True)
    plt.title(f'Distribuição {coluna}')

plt.tight_layout()
plt.show()

# Serie temporal completa
plt.figure(figsize=(16,5))
plt.plot(df_satveg['Data'], df_satveg['NDVI'], marker='o', linestyle='-')
plt.title('NDVI ao longo do tempo')
plt.xlabel('Data')
plt.ylabel('NDVI')
plt.grid(True)
plt.tight_layout()
plt.show()

# Gráfico da média mensal (sazonalidade típica)
ndvi_media_mensal = df_satveg.groupby('mes')['NDVI'].mean()

plt.figure(figsize=(10,5))
plt.plot(ndvi_media_mensal.index, ndvi_media_mensal.values, marker='o')
plt.title('Média Mensal do NDVI (Sazonalidade)')
plt.xlabel('Mês')
plt.ylabel('NDVI médio')
plt.xticks(range(1,13))
plt.grid(True)
plt.show()

# Boxplot do NDVI por mês
plt.figure(figsize=(12,6))
sns.boxplot(x='mes', y='NDVI', data=df_satveg)
plt.title('Distribuição do NDVI por mês')
plt.xlabel('Mês')
plt.ylabel('NDVI')
plt.grid(True)
plt.show()

# Heatmap Ano vs Mês do NDVI
pivot = df_satveg.pivot_table(
    index='ano', columns='mes', values='NDVI', aggfunc='mean'
)

plt.figure(figsize=(14,6))
sns.heatmap(pivot, cmap='YlGn', annot=True, fmt=".2f")
plt.title('Heatmap NDVI: Ano x Mês')
plt.xlabel('Mês')
plt.ylabel('Ano')
plt.show()

#Gráfico de linhas sobrepostas por ano
plt.figure(figsize=(12,6))
for ano, grupo in df_satveg.groupby('ano'):
    plt.plot(grupo['mes'], grupo['NDVI'], marker='o', label=ano)

plt.title('NDVI Mensal: Comparativo entre anos')
plt.xlabel('Mês')
plt.ylabel('NDVI')
plt.xticks(range(1, 13))
plt.legend(title="Ano")
plt.grid(True)
plt.tight_layout()
plt.show()

# Decomposição da série temporal (tendência + sazonalidade)
import statsmodels.api as sm

# Dados reagrupados mensalmente
ndvi_monthly = df_satveg.set_index('Data')['NDVI'].resample('M').mean().interpolate()

# Use the seasonal_decompose function from statsmodels.tsa.seasonal
decomp = sm.tsa.seasonal_decompose(ndvi_monthly, model='additive', period=12)
decomp.plot()
plt.suptitle('Decomposição série temporal do NDVI (mensal)')
plt.show()

# Relações entre variáveis (dispersão)
print("\n Dispersão - Relações entre variáveis:")
plt.figure(figsize=(16, 5))

# Gráfico 1: NDVI vs PreFiltro
plt.subplot(1, 3, 1)
plt.scatter(df_satveg['NDVI'], df_satveg['PreFiltro'], alpha=0.6, color='green' )
plt.title('NDVI vs PreFiltro')
plt.xlabel('NDVI')
plt.ylabel('PreFiltro')
plt.grid(True, linestyle='--', alpha=0.7)

# Gráfico 2: NDVI vs FlatBottom
plt.subplot(1, 3, 2)
plt.scatter(df_satveg['NDVI'], df_satveg['FlatBottom'], alpha=0.7, color='blue')
plt.title('NDVI vs FlatBottom')
plt.xlabel('NDVI')
plt.ylabel('FlatBottom')
plt.grid(True, linestyle='--', alpha=0.7)

# Gráfico 3: PreFiltro vs FlatBottom
plt.subplot(1, 3, 3)
plt.scatter(df_satveg['PreFiltro'], df_satveg['FlatBottom'], alpha=0.7, color='orange')
plt.title('PreFiltro vs FlatBottom')
plt.xlabel('PreFiltro')
plt.ylabel('FlatBottom')
plt.grid(True, linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

# Comparação de variáveis (boxplots)
print("\n Boxplots - Comparação de distribuição entre variáveis:")
plt.figure(figsize=(10, 6))
df_melt = df_satveg.melt(id_vars='Data', value_vars=colunas_numericas,
                  var_name='Métrica', value_name='Valor')
sns.boxplot(x='Métrica', y='Valor', data=df_melt)
plt.title('Distribuição de valores das métricas')
plt.grid(True)
plt.show()

# Matriz de correlação
print("\n Matriz de correlação entre as métricas:")
plt.figure(figsize=(10, 8))
corr = df_satveg[colunas_numericas].corr()
mask = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr, annot=True, cmap='coolwarm', mask=mask, vmin=-1, vmax=1)
plt.title('Matriz de correlação entre as métricas')
plt.show()

# Salvar os dados processados no diretório do Colab
processed_path = os.path.join('dados_processados', 'satveg_processado.csv')
df_satveg.to_csv(processed_path, index=False)
print(f"- Dados processados salvos em: {processed_path}")

# Opção de download
try:
    files.download(processed_path)
    print("- Arquivo 'satveg_processado.csv' disponibilizado para download.")
except Exception as e:
    print(f"- Erro ao disponibilizar arquivo para download: {e}")



"""# Dados metereológicos INMET
Optamos por fazer download dos arquivos, pois via API ia ficar muito lento

Fonte de dados https://portal.inmet.gov.br/dadoshistoricos
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import glob
import os
from google.colab import files
import zipfile

# Carregamento e Consolidação dos Dados

# Upload dos arquivos
uploaded = files.upload()

# Padrão dos arquivos
arquivos = sorted(glob.glob('Clima_Sorriso_*.csv'))

print("Arquivos encontrados:", arquivos)

# Ler e concatenar os arquivos
dfs = []
for arq in arquivos:
    print("Lendo:", arq)
    df_temp = pd.read_csv(arq, sep=";", encoding='latin1')
    dfs.append(df_temp)

df_climatotal = pd.concat(dfs, ignore_index=True)

# Converter 'DATA' para datetime
df_climatotal['DATA'] = pd.to_datetime(df_climatotal['DATA'], errors='coerce')

# Visualização inicial
print("\nBase consolidada, preview:")
print(df_climatotal.head())
print(f"\nTotal de linhas lidas: {df_climatotal.shape[0]}")

# Salvar Dados Originais

# Criar diretório se não existir
os.makedirs('dados_originais', exist_ok=True)

# Salvar arquivos originais e criar lista para compactar
arquivos_originais_salvos = []
for arq in arquivos:
    original_data = pd.read_csv(arq, sep=";", encoding='latin1')
    original_path = os.path.join('dados_originais', arq)
    original_data.to_csv(original_path, sep=';', index=False, encoding='latin1')
    arquivos_originais_salvos.append(original_path)
    print(f"Arquivo original salvo em: {original_path}")

#Tratamento dos Dados

# Validar datas
df_climatotal['DATA'] = pd.to_datetime(df_climatotal['DATA'], format='%d/%m/%Y', errors='coerce')

# Encontrar menor e maior data
menor_data = df_climatotal['DATA'].min()
maior_data = df_climatotal['DATA'].max()

print("Menor data:", menor_data.strftime('%d/%m/%Y') if pd.notna(menor_data) else "Nenhuma data")
print("Maior data:", maior_data.strftime('%d/%m/%Y') if pd.notna(maior_data) else "Nenhuma data")

# Tratar valores ausentes
df_climatotal['RADIACAO'] = df_climatotal['RADIACAO'].replace(-9999, np.nan)
df_climatotal['TEMPERATURA'] = df_climatotal['TEMPERATURA'].replace(-9999, np.nan)

# Remover coluna
df_climatotal = df_climatotal.drop('RADIACA', axis=1, errors='ignore')  # Adicionado errors='ignore'

# Tratar valores inválidos
df_climatotal.loc[df_climatotal['RADIACAO'] < 0, 'RADIACAO'] = np.nan

# Criar colunas
df_climatotal['ANO_MES'] = df_climatotal['DATA'].dt.strftime('%Y-%m')
df_climatotal['ANO'] = df_climatotal['DATA'].dt.year.astype('Int64')
df_climatotal['MES'] = df_climatotal['DATA'].dt.month.astype('Int64')

print(df_climatotal[['DATA', 'ANO', 'MES', 'ANO_MES', 'RADIACAO', 'TEMPERATURA']].head())

# Análise de nulos, duplicados e tipos

print("\nValores nulos por coluna:")
print(df_climatotal.isnull().sum())

print("\nPorcentagem de nulos:")
print(df_climatotal.isnull().mean().sort_values(ascending=False) * 100)

print("\nQtde de linhas duplicadas:", df_climatotal.duplicated().sum())

print(df_climatotal.dtypes)

# Análise Exploratória

print(df_climatotal.describe())

# Análise de outliers (RADIACAO)
print('RADIACAO → mínimo:', df_climatotal['RADIACAO'].min(), 'máximo:', df_climatotal['RADIACAO'].max())
print('Primeiros 10 valores de RADIACAO:', df_climatotal['RADIACAO'].head(10).values)

# Análise de outliers (TEMPERATURA)
print('TEMPERATURA → mínimo:', df_climatotal['TEMPERATURA'].min(), 'máximo:', df_climatotal['TEMPERATURA'].max())
print('Primeiros 10 valores de TEMPERATURA:', df_climatotal['TEMPERATURA'].head(10).values)

# Função para remover outliers
def remover_outliers_std(df, coluna, n_std=3):
    if coluna not in df.columns:
        print(f"Coluna '{coluna}' não encontrada no DataFrame.")
        return df
    media = df[coluna].mean()
    std = df[coluna].std()
    limite_superior = media + n_std * std
    limite_inferior = media - n_std * std
    df_sem_outliers = df[(df[coluna] <= limite_superior) & (df[coluna] >= limite_inferior)].copy()
    print(f"Removendo outliers de '{coluna}' (original: {len(df)}, após: {len(df_sem_outliers)})")
    return df_sem_outliers

df_climatotal = remover_outliers_std(df_climatotal, 'RADIACAO', n_std=3)
df_climatotal = remover_outliers_std(df_climatotal, 'TEMPERATURA', n_std=3)

df_climatotal = df_climatotal.reset_index(drop=True)

print(df_climatotal.describe())

# Visualização
print("\nVisualização de Dados")

# Gráficos e serie temporal
plt.figure(figsize=(15, 5))
plt.plot(df_climatotal['DATA'], df_climatotal['RADIACAO'], color='orange')
plt.xlabel('DATA')
plt.ylabel('Radiação (W/m²)')
plt.title('Radiação Solar ao Longo do Tempo')
plt.grid(True)
plt.tight_layout()
plt.show()

# Boxplot (RADIACAO total)
plt.figure(figsize=(6,5))
plt.boxplot(df_climatotal['RADIACAO'].dropna())
plt.ylabel('Radiação (W/m²)')
plt.title('Boxplot da Radiação')
plt.show()

# Boxplot ano a ano RADIACAO
plt.figure(figsize=(10,6))
df_climatotal.boxplot(column='RADIACAO', by='ANO', grid=False)
plt.xlabel('Ano')
plt.ylabel('Radiação (W/m²)')
plt.title('Boxplot da Radiação por Ano')
plt.suptitle('')
plt.tight_layout()
plt.show()

# Gráfico de dispersão - Radiação x Ano
plt.figure(figsize=(10,6))
plt.scatter(df_climatotal['ANO'], df_climatotal['RADIACAO'], alpha=0.3, color='orange')
plt.xlabel('Ano')
plt.ylabel('Radiação (W/m²)')
plt.title('Dispersão de Radiação por Ano')
plt.grid(True)
plt.tight_layout()
plt.show()

# Dispersão - Médias anuais RADIACAO
media_ano = df_climatotal.groupby('ANO')['RADIACAO'].mean().reset_index()

plt.figure(figsize=(10,6))
plt.scatter(media_ano['ANO'], media_ano['RADIACAO'], s=100, color='orange')
plt.plot(media_ano['ANO'], media_ano['RADIACAO'], color='orange', alpha=0.5)  # Linha para facilitar tendência
plt.xlabel('Ano')
plt.ylabel('Média de Radiação (W/m²)')
plt.title('Média Anual de Radiação (Dispersão)')
plt.grid(True)
plt.tight_layout()
plt.show()

# Gráfico de serie temporal TEMPERATURA
plt.figure(figsize=(15,5))
plt.plot(df_climatotal['DATA'], df_climatotal['TEMPERATURA'], color='green')
plt.xlabel('Data')
plt.ylabel('Temperatura (C)')
plt.title('Temperatura ao longo do tempo')
plt.grid(True)
plt.tight_layout()
plt.show()

# Boxplot ( TEMPERATURA total)
plt.figure(figsize=(6,5))
plt.boxplot(df_climatotal['TEMPERATURA'].dropna())
plt.ylabel('Temperatura (C)')
plt.title('Boxplot da temperatura')
plt.show()

# Boxplot ano a ano TEMPERATURA
plt.figure(figsize=(10,6))
df_climatotal.boxplot(column='TEMPERATURA', by='ANO', grid=False)
plt.xlabel('Ano')
plt.ylabel('Temperatura (C)')
plt.title('Boxplot da temperatura por ano')
plt.suptitle('')
plt.tight_layout()
plt.show()

# Gráfico de dispersão - TEMPERATURA x Ano
plt.figure(figsize=(10,6))
plt.scatter(df_climatotal['ANO'], df_climatotal['TEMPERATURA'], alpha=0.3, color='green')
plt.xlabel('Ano')
plt.ylabel('Temperatura (C)')
plt.title('Dispersão de temperatura por ano')
plt.grid(True)
plt.tight_layout()
plt.show()

# Dispersão - TEMPERATURA Médias anuais
media_ano = df_climatotal.groupby('ANO')['TEMPERATURA'].mean().reset_index()

plt.figure(figsize=(10,6))
plt.scatter(media_ano['ANO'], media_ano['TEMPERATURA'], s=100, color='green')
plt.plot(media_ano['ANO'], media_ano['TEMPERATURA'], color='green', alpha=0.5)  # Linha para facilitar tendência
plt.xlabel('Ano')
plt.ylabel('Média de temperatura (C)')
plt.title('Média anual de temperatura (Dispersão)')
plt.grid(True)
plt.tight_layout()
plt.show()

# Salvar dados processados
processed_path = os.path.join('dados_processados', 'clima_consolidado.csv')
df_climatotal.to_csv(processed_path, index=False)
print(f"DataFrame climático consolidado salvo em: {processed_path}")

# Download
try:
    files.download(processed_path)
    print("- Arquivo 'clima_consolidado.csv' disponibilizado para download.")
except Exception as e:
    print(f"- Erro ao disponibilizar arquivo para download: {e}")

# Compactar e disponibilizar arquivos originais
def compactar_e_disponibilizar_download(arquivos, nome_zip):
    with zipfile.ZipFile(f'{nome_zip}.zip', 'w', zipfile.ZIP_DEFLATED) as zipf:
        for arquivo in arquivos:
            zipf.write(arquivo, os.path.basename(arquivo))
    try:
        files.download(f'{nome_zip}.zip')
        print(f"- Arquivo '{nome_zip}.zip' compactado e disponibilizado para download.")
    except Exception as e:
        print(f"- Erro ao disponibilizar arquivo compactado para download: {e}")

compactar_e_disponibilizar_download(arquivos_originais_salvos, 'clima_originais')

"""# Produção agrícola 🌱🌽
Fonte de dados CONAB, série histórica grãos https://portaldeinformacoes.conab.gov.br/downloads/arquivos/SerieHistoricaGraos.txt


"""

# Bibliotecas necessárias
import pandas as pd
import re
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import altair as alt
import os
from google.colab import files
import zipfile

# Carregamento dos Dados

# Upload do arquivo
try:
    uploaded = files.upload()
    filename = list(uploaded.keys())[0]
    df = pd.read_csv(filename, sep=";", encoding='latin1')
except FileNotFoundError:
    print("Erro: Arquivo não encontrado. Verifique o nome e o caminho.")
    exit()
except pd.errors.EmptyDataError:
    print("Erro: O arquivo está vazio.")
    exit()
except Exception as e:
    print(f"Erro ao carregar o arquivo: {e}")
    exit()

# Verificar os nomes das colunas
print("Colunas do DataFrame carregado:")
print(df.columns)

# Criar diretório se não existir
os.makedirs('dados_originais', exist_ok=True)

# Salvar o arquivo original
original_path = os.path.join('dados_originais', filename)
df.to_csv(original_path, sep=';', index=False, encoding='latin1')
print(f"Arquivo original salvo em: {original_path}")

# Visualiza o conteúdo
print("\nVisualização correta do arquivo:")
print(df.head())

# 2. Tratamento dos Dados

# Função para renomear colunas de forma segura
def renomear_coluna_se_existir(df, coluna_original, coluna_nova):
    if coluna_original in df.columns:
        df = df.rename(columns={coluna_original: coluna_nova})
    return df

# Renomear a coluna 'UF' para 'uf' se existir
df = renomear_coluna_se_existir(df, 'UF', 'uf')

# Filtrar apenas UF = MT (Mato Grosso)
if 'uf' in df.columns:
    df = df[df['uf'].str.strip().str.upper() == 'MT'].copy()
else:
    print("Aviso: A coluna 'uf' não foi encontrada. O filtro por UF não foi aplicado.")

# Separar o ano_agricola em primeiro_ano e segundo_ano
def separa_anos(ano_agricola):
    if isinstance(ano_agricola, str) and '/' in ano_agricola:
        a1, a2 = ano_agricola.split('/')
        return a1.strip(), a2.strip()
    elif isinstance(ano_agricola, str):
        return ano_agricola.strip(), None
    else:
        return None, None

anos = df['ano_agricola'].apply(separa_anos)
df['primeiro_ano'] = anos.str[0]
df['segundo_ano'] = anos.str[1]

# Verificar se 'primeiro_ano' foi criado corretamente
print("\nColunas após separa_anos():")
print(df.columns)

# Renomear 'primeiro_ano' para 'ano' (Garantir consistência!)
df = renomear_coluna_se_existir(df, 'primeiro_ano', 'ano')

# Renomear colunas
df = renomear_coluna_se_existir(df, 'dsc_safra_previsao', 'safra')
df = renomear_coluna_se_existir(df, 'area_plantada_mil_ha', 'area_plantada')
df = renomear_coluna_se_existir(df, 'producao_mil_t', 'producao')
df = renomear_coluna_se_existir(df, 'produtividade_mil_ha_mil_t', 'produtividade')

# Corrigir caracteres na coluna safra
def padroniza_safra(s):
    if not isinstance(s, str):
        return s
    s = s.upper().strip()
    s = re.sub(r'1[ÂAªAa]*\s*SAFRA', '1ª SAFRA', s)
    s = re.sub(r'2[ÂAªAa]*\s*SAFRA', '2ª SAFRA', s)
    s = re.sub(r'3[ÂAªAa]*\s*SAFRA', '3ª SAFRA', s)
    s = re.sub(r'UNICA', 'ÚNICA', s)
    return s.title()

df['safra'] = df['safra'].apply(padroniza_safra)

# Filtrar somente produto MILHO (independente de espaços maiúsculas ou acentuação)
df = df[df['produto'].str.strip().str.upper() == 'MILHO']

# Verificar as colunas antes da seleção
print("\nColunas antes da seleção:")
print(df.columns)

# Selecionar colunas finais na ordem desejada
colunas = [
    'ano_agricola', 'ano', 'segundo_ano', 'safra',
    'uf', 'produto', 'area_plantada', 'producao', 'produtividade'
]
df_milho = df[colunas].reset_index(drop=True)

# Remover valores nulos nas colunas principais
df_milho = df_milho.dropna(subset=[
    'ano_agricola', 'ano', 'segundo_ano', 'safra',
    'area_plantada', 'producao', 'produtividade'
]).reset_index(drop=True)

# 3. Análise de Nulos e Tipos

# Print para conferir se sobraram nulos
print("\nValores nulos por coluna:")
print(df_milho.isnull().sum())

# Visualização final
print(f"\nBase consolidada: {df_milho.shape[0]} linhas x {df_milho.shape[1]} colunas.")
print(df_milho.head())
print(f"O DataFrame tem {df_milho.shape[0]} linhas e {df_milho.shape[1]} colunas.")

# Informações gerais das colunas
print("\nInformações gerais das colunas:")
df_milho.info()

# Análise Exploratória

print(df_milho.describe())

# Visualização de dados

# Distribuições (histogramas)
print("\nHistograma - Distribuição das variáveis:")
plt.figure(figsize=(15, 5))

colunas_numericas = ['area_plantada', 'producao', 'produtividade']

for i, coluna in enumerate(colunas_numericas):
    plt.subplot(1, 3, i + 1)
    sns.histplot(df_milho[coluna], kde=True)
    plt.title(f'Distribuição {coluna}')

plt.tight_layout()
plt.show()

# Séries temporais geral
print("\nEvolução temporal das métricas:")
plt.figure(figsize=(14, 6))

# Use 'primeiro_ano' se existir, caso contrário use 'ano'
ano_coluna = 'primeiro_ano' if 'primeiro_ano' in df_milho.columns else 'ano'

for coluna in colunas_numericas:
    plt.plot(df_milho[ano_coluna], df_milho[coluna], label=coluna)

plt.title('Evolução temporal das métricas')
plt.xlabel('Ano')
plt.ylabel('Valor')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# Séries temporais de 2015 em diante
print("\nEvolução temporal das métricas (2015 em diante):")

# Depuração: Verificar colunas e tipo de dado
print("\nColunas de df_milho antes da conversão:")
print(df_milho.columns)
if 'primeiro_ano' in df_milho.columns:
    print(f"Tipo de dado de primeiro_ano: {df_milho['primeiro_ano'].dtype}")
else:
    print("Aviso: A coluna 'primeiro_ano' não foi encontrada.")

# Corrigir a coluna de ano se necessário
ano_coluna = 'primeiro_ano' if 'primeiro_ano' in df_milho.columns else 'ano'
df_milho[ano_coluna] = pd.to_numeric(df_milho[ano_coluna], errors='coerce')

df_2015_em_diante = df_milho[df_milho[ano_coluna] >= 2015].copy()

print(f"Quantidade de linhas de 2015 em diante: {df_2015_em_diante.shape[0]}")

# Depuração: Verificar se o DataFrame está vazio
if df_2015_em_diante.empty:
    print("DataFrame df_2015_em_diante está vazio!")
else:
    plt.figure(figsize=(14, 6))
    for coluna in colunas_numericas:
        plt.plot(df_2015_em_diante[ano_coluna], df_2015_em_diante[coluna], marker='o', label=coluna)
    plt.title('Evolução das métricas (2015 em diante)')
    plt.xlabel('Ano')
    plt.ylabel('Valor')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

# Comparação de variáveis (boxplots)
print("\nBoxplots - Comparação de distribuição entre variáveis (escalas separadas):")
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
sns.boxplot(y=df_milho['area_plantada'])
plt.title('Área Plantada')
plt.grid(True, linestyle='--', alpha=0.7)

plt.subplot(1, 3, 2)
sns.boxplot(y=df_milho['producao'])
plt.title('Produção')
plt.grid(True, linestyle='--', alpha=0.7)

plt.subplot(1, 3, 3)
sns.boxplot(y=df_milho['produtividade'])
plt.title('Produtividade')
plt.grid(True, linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

# Boxplots normalizados para comparação direta
print("\nBoxplots - Distribuição normalizada para comparação entre variáveis:")
plt.figure(figsize=(10, 6))

# Use 'primeiro_ano' se existir, caso contrário use 'ano'
ano_coluna = 'primeiro_ano' if 'primeiro_ano' in df_milho.columns else 'ano'

df_melt = df_milho.melt(id_vars=ano_coluna, value_vars=colunas_numericas,
                        var_name='Métrica', value_name='Valor')

df_norm = df_milho.copy()
for coluna in colunas_numericas:
    df_norm[coluna] = (df_milho[coluna] - df_milho[coluna].min()) / (df_milho[coluna].max() - df_milho[coluna].min())

df_melt_norm = df_norm.melt(id_vars=ano_coluna, value_vars=colunas_numericas,
                            var_name='Métrica', value_name='Valor Normalizado')

sns.boxplot(x='Métrica', y='Valor Normalizado', data=df_melt_norm)
plt.title('Distribuição normalizada das variáveis agrícolas')
plt.grid(True, linestyle='--', alpha=0.7)
plt.ylabel('Valores normalizados (0-1)')
plt.show()

# Relações entre variáveis (dispersão)
print("\nDispersão - Relações entre variáveis:")
plt.figure(figsize=(16, 5))

plt.subplot(1, 3, 1)
plt.scatter(df_milho['area_plantada'], df_milho['producao'], alpha=0.6, color='green')
plt.title('Área Plantada vs Produção')
plt.xlabel('Área Plantada (mil ha)')
plt.ylabel('Produção (mil t)')
plt.grid(True, linestyle='--', alpha=0.7)

plt.subplot(1, 3, 2)
plt.scatter(df_milho['area_plantada'], df_milho['produtividade'], alpha=0.6, color='blue')
plt.title('Área Plantada vs Produtividade')
plt.xlabel('Área Plantada (mil ha)')
plt.ylabel('Produtividade (t/ha)')
plt.grid(True, linestyle='--', alpha=0.7)

plt.subplot(1, 3, 3)
plt.scatter(df_milho['produtividade'], df_milho['producao'], alpha=0.6, color='orange')
plt.title('Produtividade vs Produção')
plt.xlabel('Produtividade (t/ha)')
plt.ylabel('Produção (mil t)')
plt.grid(True, linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

# Boxplots agrupados por safra
print("\nBoxplots - Evolução por safra:")
plt.figure(figsize=(15, 12))

# Use 'primeiro_ano' se existir, caso contrário use 'ano'
ano_coluna = 'primeiro_ano' if 'primeiro_ano' in df_milho.columns else 'ano'

plt.subplot(3, 1, 1)
sns.boxplot(x=ano_coluna, y='area_plantada', data=df_milho)
plt.title('Área Plantada por Safra')
plt.grid(True, linestyle='--', alpha=0.7)
plt.xticks(rotation=45)

plt.subplot(3, 1, 2)
sns.boxplot(x=ano_coluna, y='producao', data=df_milho)
plt.title('Produção por Safra')
plt.grid(True, linestyle='--', alpha=0.7)
plt.xticks(rotation=45)

plt.subplot(3, 1, 3)
sns.boxplot(x=ano_coluna, y='produtividade', data=df_milho)
plt.title('Produtividade por Safra')
plt.grid(True, linestyle='--', alpha=0.7)
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

# Matriz de correlação
print("\nMatriz de correlação entre as métricas:")
plt.figure(figsize=(10, 8))
corr = df_milho[colunas_numericas].corr()
mask = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr, annot=True, cmap='coolwarm', mask=mask, vmin=-1, vmax=1)
plt.title('Matriz de correlação entre as métricas')
plt.show()

import pandas as pd
import os
from google.colab import files
import zipfile

def salvar_dataframe(df, nome_arquivo, diretorio='dados_processados', index=False):
    """Salva um DataFrame em um arquivo CSV."""
    caminho_arquivo = os.path.join(diretorio, nome_arquivo)
    df.to_csv(caminho_arquivo, index=index)
    print(f"DataFrame salvo em: {caminho_arquivo}")
    return caminho_arquivo

def disponibilizar_download(caminho_arquivo):
    """Disponibiliza um arquivo para download."""
    try:
        files.download(caminho_arquivo)
        print(f"- Arquivo '{os.path.basename(caminho_arquivo)}' disponibilizado para download.")
    except Exception as e:
        print(f"- Erro ao disponibilizar arquivo '{os.path.basename(caminho_arquivo)}' para download: {e}")

def compactar_e_disponibilizar_download(arquivos, nome_zip):
    """Compacta uma lista de arquivos em um arquivo ZIP e disponibiliza para download."""
    caminho_zip = f'{nome_zip}.zip'
    try:
        with zipfile.ZipFile(caminho_zip, 'w', zipfile.ZIP_DEFLATED) as zipf:
            for arquivo in arquivos:
                zipf.write(arquivo, os.path.basename(arquivo))
        disponibilizar_download(caminho_zip)
        print(f"- Arquivo '{caminho_zip}' compactado e disponibilizado para download.")
    except Exception as e:
        print(f"- Erro ao compactar e disponibilizar arquivos para download: {e}")

# --- Main ---

# Exemplo de uso:
# (Assumindo que df_milho e original_path já estão definidos)

# 6. Salvar e Download

# Salvar dados processados
processed_path = salvar_dataframe(df_milho, 'milho.csv')

# Download dos dados processados
disponibilizar_download(processed_path)

# Compactar e disponibilizar arquivo original (opcional)
compactar_e_disponibilizar_download([original_path], 'milho_original')

print(df_milho.head())

"""# Etapa 2 – Extração de Informações Relevantes:

*   Definir variáveis-chave a serem utilizadas no modelo, a partir da análise
exploratória dos dados.
*   Analisar a relação entre NDVI e produtividade agrícola, identificando os períodos críticos de crescimento da cultura.
*   Aplicar técnicas de segmentação para destacar áreas específicas de cultivo na imagem de satélite.
"""

import pandas as pd
import numpy as np
import os
import re

def padronizar_nomes_colunas(df):
    """Padroniza os nomes das colunas (minúsculas, underscores)."""
    df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
    return df

def selecionar_colunas_satveg(df):
    """Seleciona as colunas relevantes do DataFrame SatVeg."""
    colunas_relevantes = ['data', 'ano', 'ndvi_media_mensal']
    colunas_existentes = [col for col in colunas_relevantes if col in df.columns]
    return df[colunas_existentes].copy()

def selecionar_colunas_clima(df):
    """Seleciona as colunas relevantes do DataFrame Clima."""
    colunas_relevantes = ['data', 'ano', 'temperatura', 'radiacao']
    colunas_existentes = [col for col in colunas_relevantes if col in df.columns]
    return df[colunas_existentes].copy()

def selecionar_colunas_milho(df):
    """Seleciona as colunas relevantes do DataFrame Milho."""
    colunas_relevantes = ['ano', 'ano_safra', 'area_plantada', 'producao', 'produtividade']
    colunas_existentes = [col for col in colunas_relevantes if col in df.columns]
    return df[colunas_existentes].copy()

def calcular_ndvi_medio_anual(df):
    """Calcula o NDVI médio anual."""
    ndvi_medio_ano = (
        df.groupby('ano')['ndvi_media_mensal']
        .mean()
        .reset_index()
        .rename(columns={'ndvi_media_mensal': 'ndvi_medio_ano'})
    )
    return ndvi_medio_ano

def interpolar_dados_clima(df):
    """Interpola os dados climáticos."""
    if 'temperatura' in df.columns:
        df['temperatura'] = df['temperatura'].interpolate(method='linear', limit_direction='both')
        df['imputado_temp'] = df['temperatura'].isnull()
    if 'radiacao' in df.columns:
        df['radiacao'] = df['radiacao'].interpolate(method='linear', limit_direction='both')
        df['imputado_rad'] = df['radiacao'].isnull()
    return df

def imputar_clima_faltante(df, anos_faltantes, colunas_clima):
    """Imputa dados climáticos faltantes pela média dos outros anos."""
    for ano in anos_faltantes:
        for coluna in colunas_clima:
            df.loc[df['ano'] == ano, coluna] = df[df['ano'] != ano][coluna].mean()
    return df

def merge_dataframes(df_milho, df_ndvi, df_clima, ano_inicio, ano_fim):
    """Realiza o merge dos DataFrames."""
    try:
        # Filtrar df_milho pelos anos de análise
        df_milho_filtrado = df_milho[(df_milho['ano'] >= ano_inicio) & (df_milho['ano'] <= ano_fim)].copy()

        # Merge Milho com NDVI
        base = pd.merge(df_milho_filtrado, df_ndvi, on='ano', how='left')

        # Merge com Clima
        base = pd.merge(base, df_clima, on='ano', how='left')

        return base
    except KeyError as e:
        print(f"Erro ao realizar o merge: Coluna não encontrada - {e}")
        return None

# --- Main ---

# 1. Carregar os DataFrames (Certifique-se de que os caminhos estão corretos)
df_satveg = pd.read_csv('dados_processados/satveg_processado.csv')
df_climatotal = pd.read_csv('dados_processados/clima_consolidado.csv')
df_milho = pd.read_csv('dados_processados/milho.csv')

# 2. Padronizar Nomes
df_satveg = padronizar_nomes_colunas(df_satveg)
df_climatotal = padronizar_nomes_colunas(df_climatotal)
df_milho = padronizar_nomes_colunas(df_milho)

# 3. Selecionar Colunas Relevantes
df_satveg = selecionar_colunas_satveg(df_satveg)
df_climatotal = selecionar_colunas_clima(df_climatotal)
df_milho = selecionar_colunas_milho(df_milho)

# 4. Renomear Colunas (Garantir que 'ano' exista em todos)
if 'primeiro_ano' in df_milho.columns:
    df_milho.rename(columns={'primeiro_ano': 'ano'}, inplace=True)
if 'data' in df_satveg.columns:
    df_satveg['ano'] = pd.to_datetime(df_satveg['data']).dt.year
if 'data' in df_climatotal.columns:
    df_climatotal['ano'] = pd.to_datetime(df_climatotal['data']).dt.year

# 5. Calcular NDVI Médio Anual
df_ndvi_medio = calcular_ndvi_medio_anual(df_satveg)

# 6. Definir Período e Anos Faltantes
ano_inicio = 2015
ano_fim = df_climatotal['ano'].max()  # Último ano disponível nos dados de clima
anos_faltantes = [2021, 2022]
colunas_clima = ['temperatura', 'radiacao']

# 7. Realizar os Merges
base = merge_dataframes(df_milho, df_ndvi_medio, df_climatotal, ano_inicio, ano_fim)

# 8. Interpolar Dados Climáticos
if base is not None:
    base = base.sort_values('ano').reset_index(drop=True)
    base = interpolar_dados_clima(base)

    # 9. Imputar Dados Climáticos Faltantes
    base = imputar_clima_faltante(base, anos_faltantes, colunas_clima)


    # Salvar
    processed_path = os.path.join('dados_processados', 'base.csv')
    base.to_csv(processed_path, index=False)
    print(f"- Dados processados salvos como '{processed_path}'")
else:
    print("Erro: Não foi possível realizar o merge dos DataFrames.")

# Definir variaveis chave
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

def realizar_eda(df, colunas_numericas):
    """Realiza análise exploratória de dados."""

    print("\n--- Estatísticas Descritivas ---")
    print(df[colunas_numericas].describe())

    print("\n--- Visualizações ---")
    for coluna in colunas_numericas:
        plt.figure(figsize=(8, 5))
        sns.histplot(df[coluna], kde=True)
        plt.title(f"Distribuição de {coluna}")
        plt.show()

    plt.figure(figsize=(10, 8))
    sns.heatmap(df[colunas_numericas].corr(), annot=True, cmap="coolwarm")
    plt.title("Matriz de Correlação")
    plt.show()


def engenharia_features(df):
    """Cria novas variáveis (engenharia de features)."""

    # Exemplo: Criar interação entre temperatura e radiação
    if 'temperatura' in df.columns and 'radiacao' in df.columns:
        df['temp_rad'] = df['temperatura'] * df['radiacao']

    # Exemplo: Criar lag do NDVI (se 'ndvi_medio_ano' existir)
    if 'ndvi_medio_ano' in df.columns:
        df['ndvi_lag_1'] = df['ndvi_medio_ano'].shift(1)  # Lag de 1 ano

    return df


def selecionar_variaveis(df, variavel_alvo, colunas_candidatas):
    """Seleciona as variáveis mais relevantes."""

    # Verificar tipos de dados antes da correlação
    print("\nTipos de dados antes da correlação:")
    print(df[colunas_candidatas + [variavel_alvo]].dtypes)

    # Converter colunas não numéricas para numéricas (se necessário)
    for coluna in colunas_candidatas + [variavel_alvo]:
        if df[coluna].dtype == 'object':
            try:
                df[coluna] = pd.to_numeric(df[coluna], errors='coerce')
                print(f"Coluna '{coluna}' convertida para numérico.")
            except ValueError as e:
                print(f"Aviso: Não foi possível converter a coluna '{coluna}' para numérico: {e}")

    # Calcular correlação (após a conversão)
    correlacoes = df[colunas_candidatas + [variavel_alvo]].corr()[variavel_alvo].abs().sort_values(ascending=False)
    variaveis_selecionadas = list(correlacoes[1:6].index)  # Top 5 (excluindo a própria variável alvo)
    print("\nVariáveis selecionadas (correlação):", variaveis_selecionadas)

    return variaveis_selecionadas

# 1. Carregar e processar dados (como você já tem)

# 2. Análise Exploratória
colunas_numericas = ['ndvi_medio_ano', 'temperatura', 'radiacao', 'area_plantada', 'producao', 'produtividade']  # Ajuste conforme suas colunas
realizar_eda(base, colunas_numericas)

# 3. Engenharia de Features
base = engenharia_features(base)

# 4. Seleção de Variáveis
variavel_alvo = 'produtividade'
colunas_candidatas = [col for col in base.columns if col not in ['ano', 'ano_safra', variavel_alvo]]  # Ajuste conforme necessário
variaveis_selecionadas = selecionar_variaveis(base, variavel_alvo, colunas_candidatas)

# Agora você pode usar 'variaveis_selecionadas' para treinar seu modelo
print("\nVariáveis finais para modelo:", variaveis_selecionadas)

"""Analisar a relação entre NDVI e produtividade agrícola, identificando os períodos críticos de crescimento da cultura.

"""

# Análise da Relação entre NDVI e Produtividade
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

def analisar_relacao_ndvi_produtividade(df):
    """Analisa a relação entre NDVI e produtividade."""

    # 1. Correlação Anual
    if 'ndvi_medio_ano' in df.columns and 'produtividade' in df.columns:
        correlacao_anual = df['ndvi_medio_ano'].corr(df['produtividade'])
        print(f"\nCorrelação entre NDVI médio anual e Produtividade: {correlacao_anual:.2f}")

        plt.figure(figsize=(8, 6))
        sns.scatterplot(x='ndvi_medio_ano', y='produtividade', data=df)
        plt.title('Relação entre NDVI médio anual e Produtividade')
        plt.xlabel('NDVI médio anual')
        plt.ylabel('Produtividade')
        plt.show()

    # 2. Correlação Mensal (Se você tiver dados de NDVI mensal)

    if 'ndvi_mes_01' in df.columns and 'produtividade' in df.columns:
         correlacoes_mensais = df[['ndvi_mes_01', 'ndvi_mes_02', ..., 'produtividade']].corr()['produtividade'].drop('produtividade')
         print("\nCorrelação entre NDVI mensal e Produtividade:")
         print(correlacoes_mensais)
         correlacoes_mensais.plot(kind='bar', figsize=(10, 5))
         plt.title('Correlação entre NDVI mensal e Produtividade')
         plt.show()

    # 3. Análise de Lags
    if 'ndvi_medio_ano' in df.columns and 'produtividade' in df.columns:
        df['ndvi_lag_1'] = df['ndvi_medio_ano'].shift(1)
        correlacao_lag_1 = df['ndvi_lag_1'].corr(df['produtividade'])
        print(f"\nCorrelação entre NDVI (lag 1 ano) e Produtividade: {correlacao_lag_1:.2f}")

        plt.figure(figsize=(8, 6))
        sns.scatterplot(x='ndvi_lag_1', y='produtividade', data=df)
        plt.title('Relação entre NDVI (lag 1 ano) e Produtividade')
        plt.xlabel('NDVI (lag 1 ano)')
        plt.ylabel('Produtividade')
        plt.show()

    # 4. Modelagem Simples (Exemplo: Regressão Linear)
    if 'ndvi_medio_ano' in df.columns and 'produtividade' in df.columns:
        from sklearn.linear_model import LinearRegression
        model = LinearRegression()
        model.fit(df[['ndvi_medio_ano']].fillna(0), df['produtividade'].fillna(0))  # Preencher NaN com 0 para o exemplo
        print(f"\nCoeficiente da Regressão Linear: {model.coef_[0]:.2f}")
        print(f"Intercepto da Regressão Linear: {model.intercept_:.2f}")

        plt.figure(figsize=(8, 6))
        sns.scatterplot(x='ndvi_medio_ano', y='produtividade', data=df)
        plt.plot(df['ndvi_medio_ano'], model.predict(df[['ndvi_medio_ano']].fillna(0)), color='red')
        plt.title('Regressão Linear: NDVI vs. Produtividade')
        plt.xlabel('NDVI médio anual')
        plt.ylabel('Produtividade')
        plt.show()



analisar_relacao_ndvi_produtividade(base)

# Técnicas de Segmentação
!pip install rasterio
import rasterio
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from skimage import filters, segmentation, color
from osgeo import gdal
from google.colab import files
import os

def carregar_imagens():
    """
    Carrega imagens RGB e NDVI através do botão de upload do Colab.

    Returns:
        Dicionário com as imagens carregadas
    """
    print("Por favor, clique no botão abaixo para fazer upload dos arquivos sorriso_rgb.tif e sorriso_ndvi.tif")

    # Mostra o botão de upload diretamente no notebook
    uploaded = files.upload()

    imagens = {}

    # Processar os arquivos enviados
    for nome_arquivo, conteudo in uploaded.items():
        print(f"Arquivo recebido: {nome_arquivo}")

        # Salvar o arquivo localmente (opcional, se precisar usar os arquivos depois)
        # with open(nome_arquivo, 'wb') as f:
        #     f.write(conteudo)

        # Carregar baseado no tipo de arquivo
        try:
            if 'rgb' in nome_arquivo.lower():
                # Carregar imagem RGB
                with rasterio.open(nome_arquivo) as src:
                    rgb_raw = src.read()
                    # Reorganizar para formato de visualização (H, W, C)
                    rgb = np.dstack((rgb_raw[0], rgb_raw[1], rgb_raw[2]))
                    # Normalizar para visualização
                    rgb_norm = np.clip(rgb/255.0, 0, 1)

                    imagens['rgb_raw'] = rgb_raw
                    imagens['rgb'] = rgb_norm
                    print(f"✓ Imagem RGB carregada com sucesso! Formato: {rgb.shape}")

            elif 'ndvi' in nome_arquivo.lower():
                # Carregar imagem NDVI
                with rasterio.open(nome_arquivo) as src:
                    ndvi_raw = src.read(1)
                    imagens['ndvi_raw'] = ndvi_raw
                    print(f"✓ Imagem NDVI carregada com sucesso! Formato: {ndvi_raw.shape}")
            else:
                print(f"Tipo de arquivo não reconhecido: {nome_arquivo}")

        except Exception as e:
            print(f" Erro ao processar {nome_arquivo}: {str(e)}")

    # Verificar se foram carregadas as imagens necessárias
    if 'rgb' in imagens and 'ndvi_raw' in imagens:
        print("\n✓ Todas as imagens necessárias foram carregadas!")
    else:
        print("\n Nem todas as imagens necessárias foram carregadas.")
        print("Imagens disponíveis:", list(imagens.keys()))

    return imagens

def mostrar_imagens_carregadas(imagens):
    plt.figure(figsize=(15, 6))

    # Mostrar RGB se disponível
    if 'rgb' in imagens:
        plt.subplot(1, 2, 1)
        plt.title("Imagem RGB")
        plt.imshow(imagens['rgb'])
        plt.axis('off')

    # Mostrar NDVI se disponível
    if 'ndvi_raw' in imagens:
        plt.subplot(1, 2, 2)
        plt.title("NDVI")
        plt.imshow(imagens['ndvi_raw'], cmap='RdYlGn')
        plt.colorbar(label='NDVI')
        plt.axis('off')

    plt.tight_layout()
    plt.show()

!pip install rasterio
import rasterio
import numpy as np
import matplotlib.pyplot as plt
import os
from sklearn.cluster import KMeans
from skimage import filters, segmentation, color
from osgeo import gdal

# Certifique-se de que o diretório 'dados_processados' exista
os.makedirs('/content/dados_processados', exist_ok=True)

def segmentar_por_limiar(ndvi_imagem, limiares):
    """Segmenta a imagem NDVI por limiares."""
    segmentos = np.zeros_like(ndvi_imagem, dtype=np.uint8)
    for classe, limiar in limiares.items():
        if classe == 'água':
            segmentos[ndvi_imagem <= limiar] = 1
        elif classe == 'solo_nu':
            segmentos[(ndvi_imagem > limiares['água']) & (ndvi_imagem <= limiar)] = 2
        elif classe == 'veg_esparsa':
            segmentos[(ndvi_imagem > limiares['solo_nu']) & (ndvi_imagem <= limiar)] = 3
        elif classe == 'veg_densa':
            segmentos[ndvi_imagem > limiares['veg_esparsa']] = 4
    return segmentos

def segmentar_por_kmeans(imagem, k=5):
    """Segmenta a imagem usando K-means."""
    altura, largura = imagem.shape
    X = imagem.reshape(-1, 1)
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(X)
    return labels.reshape(altura, largura)

def segmentar_watershed(imagem):
    """Segmenta a imagem usando Watershed."""
    edges = filters.sobel(imagem)
    markers = np.zeros_like(imagem, dtype=np.int32)
    markers[imagem < 0.2] = 1
    markers[imagem > 0.6] = 2
    watershed_segments = segmentation.watershed(edges, markers)
    return watershed_segments

def extrair_estatisticas_por_segmento(imagem, segmentos):
    """Extrai estatísticas (média, desvio padrão) da imagem por segmento."""
    estatisticas = {}
    for i in np.unique(segmentos):
        if i != 0:  # Ignorar o fundo (se houver)
            mascara = segmentos == i
            estatisticas[i] = {
                'mean': np.mean(imagem[mascara]),
                'std': np.std(imagem[mascara])
            }
    return estatisticas

def salvar_segmentacao(segmentos, caminho_arquivo, original_imagem_path=None):
    """Salva a segmentação como GeoTIFF."""
    try:
        if original_imagem_path:
            # Não precisamos abrir a imagem original novamente, pois já está em 'imagens'
            altura, largura = imagens['ndvi_raw'].shape
            profile = {
                'driver': 'GTiff',
                'height': altura,
                'width': largura,
                'count': 1,
                'dtype': rasterio.uint8,
                'crs': None,  # Defina o CRS se você tiver essa informação
                'transform': None  # Defina a transformação se você tiver essa informação
            }
        else:
            altura, largura = segmentos.shape
            profile = {
                'driver': 'GTiff',
                'height': altura,
                'width': largura,
                'count': 1,
                'dtype': rasterio.uint8
            }
        with rasterio.open(caminho_arquivo, 'w', **profile) as dst:
            dst.write(segmentos.astype(profile['dtype']), 1)
        print(f"Segmentação salva em: {caminho_arquivo}")
    except rasterio.RasterioIOError as e:
        print(f"Erro ao salvar GeoTIFF: {e}. Verifique se o caminho '{caminho_arquivo}' é válido.")
    except Exception as e:
        print(f"Erro inesperado ao salvar GeoTIFF: {e}")

#
ndvi_path = '/content/dados_processados/sorriso_ndvi.tif'
rgb_path = '/content/dados_processados/sorriso_rgb.tif'


# Assumindo que 'imagens' já foi carregado na Etapa 1
# imagens = carregar_imagens()  # REMOVIDO: Não precisamos carregar novamente

# Mostrar uma prévia das imagens
# if len(imagens) > 0:
#     mostrar_imagens_carregadas(imagens) # REMOVIDO: Assumindo que já foi mostrado

ndvi_imagem = imagens.get('ndvi_raw')
rgb_imagem = imagens.get('rgb')

if ndvi_imagem is not None:
    # Segmentação por Limiar
    limiares_ndvi = {'água': 0.1, 'solo_nu': 0.2, 'veg_esparsa': 0.4, 'veg_densa': 0.6}
    segmentos_limiar = segmentar_por_limiar(ndvi_imagem, limiares_ndvi)
    salvar_segmentacao(segmentos_limiar, '/content/dados_processados/segmentos_limiar.tif')

    # Segmentação por K-means
    segmentos_kmeans = segmentar_por_kmeans(ndvi_imagem, k=5)
    salvar_segmentacao(segmentos_kmeans, '/content/dados_processados/segmentos_kmeans.tif')

    # Segmentação Watershed
    segmentos_watershed = segmentar_watershed(ndvi_imagem)
    salvar_segmentacao(segmentos_watershed, '/content/dados_processados/segmentos_watershed.tif')

    # 4. Extrair Estatísticas
    estatisticas_limiar = extrair_estatisticas_por_segmento(ndvi_imagem, segmentos_limiar)
    print("\nEstatísticas por segmento (limiar):", estatisticas_limiar)

    # Visualizar (Opcional)
    plt.figure(figsize=(15, 5))
    plt.subplot(1, 3, 1); plt.imshow(segmentos_limiar); plt.title('Limiar')
    plt.subplot(1, 3, 2); plt.imshow(segmentos_kmeans); plt.title('K-means')
    plt.subplot(1, 3, 3); plt.imshow(segmentos_watershed); plt.title('Watershed')
    plt.show()

else:
    print("Erro: Não foi possível acessar as imagens necessárias.")

# AGORA PRECISA JUNTAR OS DADOS DAS BASES COM AS INFORMAÇÕES DAS IMAGENS



# SO ESTA CONSIDERANDO BASE DE DADOS NÃO FAZ SENTIDO
# Estratégias para Integrar Dados em Diferentes Escalas

# Agregação Espacial, considera que a Fazenda São José é representativa para a região de Sorriso-MT

import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Opção 1

# 1. Carregar o DataFrame base
base = pd.read_csv('dados_processados/base.csv')

# 2. Selecionar Variáveis (Exemplo)
variaveis_chave = [
    'ndvi_medio_ano',
    'temperatura',
    'radiacao',
    'area_plantada'
    # Adicione outras variáveis que você considerar relevantes
]
variavel_alvo = 'produtividade'

# 3. Preparar os dados para modelagem
X = base[variaveis_chave]
y = base[variavel_alvo]

# 4. Dividir os dados em conjuntos de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 5. Criar e treinar o modelo (Random Forest como exemplo)
model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train)

# 6. Fazer previsões e avaliar o modelo
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MSE: {mse}")
print(f"R2: {r2}")

# 7. Salvar o modelo (opcional)
# import joblib
# joblib.dump(model, 'modelo_produtividade.joblib')

# Opção 2
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
import xgboost as xgb
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import joblib


# 1. Carregar o DataFrame base
base = pd.read_csv('dados_processados/base.csv')

# 2. Selecionar Variáveis (Exemplo)
variaveis_chave = [
    'ndvi_medio_ano',
    'temperatura',
    'radiacao',
    'area_plantada'
    # Adicione outras variáveis que você considerar relevantes
]
variavel_alvo = 'produtividade'

# 3. Preparar os dados para modelagem
X = base[variaveis_chave]
y = base[variavel_alvo]

# 4. Dividir os dados em conjuntos de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# 5. Definir Modelos e Hiperparâmetros
modelos = {
    'Regressão Linear': {
        'model': LinearRegression(),
        'params': {}  # Sem hiperparâmetros para Regressão Linear
    },
    'Random Forest': {
        'model': RandomForestRegressor(random_state=42),
        'params': {
            'n_estimators': [50, 100, 200],
            'max_depth': [None, 10, 20],
            'min_samples_split': [2, 5, 10]
        }
    },
    'SVR': {
        'model': SVR(),
        'params': {
            'C': [0.1, 1, 10],
            'kernel': ['linear', 'rbf'],
            'gamma': ['scale', 'auto']
        }
    },
    'XGBoost': {
        'model': xgb.XGBRegressor(objective='reg:squarederror', random_state=42),
        'params': {
            'n_estimators': [100, 500, 1000],
            'learning_rate': [0.01, 0.05, 0.1],
            'max_depth': [3, 5, 7]
        }
    }
}

# 6. Treinar, Avaliar e Ajustar Hiperparâmetros
melhores_modelos = {}
for nome, config in modelos.items():
    print(f"\n--- {nome} ---")
    grid_search = GridSearchCV(config['model'], config['params'], cv=5, scoring='neg_mean_squared_error')
    grid_search.fit(X_train, y_train)

    melhor_modelo = grid_search.best_estimator_
    y_pred = melhor_modelo.predict(X_test)

    mse = mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, y_pred)

    print(f"Melhores Hiperparâmetros: {grid_search.best_params_}")
    print(f"MSE: {mse:.2f}, MAE: {mae:.2f}, RMSE: {rmse:.2f}, R2: {r2:.2f}")

    melhores_modelos[nome] = melhor_modelo

# 7. Comparar Modelos e Escolher o Melhor
print("\n--- Comparação de Modelos ---")
melhor_nome = None
melhor_r2 = float('-inf')  # Inicializar com o menor valor possível
for nome, modelo in melhores_modelos.items():
    y_pred = modelo.predict(X_test)
    r2 = r2_score(y_test, y_pred)
    print(f"{nome}: R2 = {r2:.2f}")
    if r2 > melhor_r2:
        melhor_nome = nome
        melhor_r2 = r2

print(f"\nMelhor Modelo: {melhor_nome} (R2 = {melhor_r2:.2f})")

# 8. Salvar o Melhor Modelo (Opcional)
# joblib.dump(melhores_modelos[melhor_nome], 'melhor_modelo_produtividade.joblib')

# Janelas móveis de NDVI médio
for mes_inicio in range(1, 11):
    colunas = [f'ndvi_mes_{mes_inicio:02d}', f'ndvi_mes_{mes_inicio+1:02d}', f'ndvi_mes_{mes_inicio+2:02d}']
    if all(col in analise.columns for col in colunas):
        analise[f'janela_{mes_inicio:02d}_{mes_inicio+2:02d}'] = analise[colunas].mean(axis=1)

# Repetir a análise de correlação para as novas colunas
cor_janelas = {col: analise[col].corr(analise['produtividade'])
               for col in analise.columns if col.startswith('janela_')}
cor_janelas = pd.Series(cor_janelas).sort_values(ascending=False)
print('- Correlação das janelas de NDVI com a produtividade -')
print(cor_janelas)

cor_janelas.plot(kind='bar', figsize=(10,4), title='Correlações NDVI janelas vs. produtividade')
plt.ylabel('Correlação')
plt.show()

plt.show()
print("\nJan/Mar apresentou a maior correlação.\n")
print("Conclusão: Vigor da vegetação no início do ciclo é determinante para produtividade.")

"""Aplicar técnicas de segmentação para destacar áreas específicas de cultivo na imagem de satélite."""

# Instalar pacotes necessários
!pip install earthengine-api geemap

# Importar bibliotecas
import ee
import geemap
import os
from google.colab import files

# Autenticar e inicializar o Earth Engine
ee.Authenticate()
ee.Initialize(project="pipoca-452815")

# Definir área de interesse: Sorriso-MT
sorriso = ee.Geometry.Point(-55.71, -12.55).buffer(30000)  # 30km de buffer

# Definir período de uma safra completa
start_date = '2023-10-01'  # Início do plantio da soja
end_date = '2024-04-30'    # Após colheita da soja e possível safrinha

# Obter coleção Sentinel-2 com bandas específicas
s2 = ee.ImageCollection('COPERNICUS/S2_SR') \
    .filterDate(start_date, end_date) \
# Obter coleção Sentinel-2 com bandas específicas
s2 = ee.ImageCollection('COPERNICUS/S2_SR') \
    .filterDate(start_date, end_date) \
    .filterBounds(sorriso) \
    .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 20)) \
    .select(['B2', 'B3', 'B4', 'B8']) \
    .median()  # Mediana para remover nuvens

# Calcular NDVI
ndvi = s2.normalizedDifference(['B8', 'B4']).rename('NDVI')
s2 = s2.addBands(ndvi)

# Visualizar no mapa
Map = geemap.Map()
Map.centerObject(sorriso, 10)
Map.addLayer(s2, {'bands': ['B4', 'B3', 'B2'], 'min': 0, 'max': 3000}, 'RGB Natural')
Map.addLayer(ndvi, {'min': 0, 'max': 0.8, 'palette': ['white', 'yellow', 'green']}, 'NDVI')
Map

# Montar o Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Definir pasta no Drive
drive_folder = "EarthEngine_Exports"  # Nome da pasta que será criada no Drive

# Função para exportar para o Drive
def export_to_drive(image, name, region, scale=30):
    task = ee.batch.Export.image.toDrive(
        image=image,
        description=name,
        folder=drive_folder,
        fileNamePrefix=name,
        region=region.getInfo()['coordinates'],
        scale=scale,
        maxPixels=1e9
    )
    task.start()
    print(f"Exportando {name} para o Google Drive...")
    return task

# Exportar imagens para o Drive
export_to_drive(
    s2.select(['B4', 'B3', 'B2']).divide(3000).multiply(255).byte(),
    "sorriso_rgb",
    sorriso,
    scale=30  # Resolução reduzida para tornar o arquivo menor
)

export_to_drive(
    ndvi,
    "sorriso_ndvi",
    sorriso,
    scale=30
)

print("\nImagens estão sendo exportadas para seu Google Drive.")
print("Este processo pode levar alguns minutos. As imagens estarão na pasta", drive_folder)
print("Você pode verificar o progresso em: https://code.earthengine.google.com/tasks")
print("Quando as tarefas estiverem concluídas, você poderá acessar os arquivos no seu Google Drive")

"""Upload das imagens do Drive e aplicação das técnicas de segmentação"""

# Carregamento de imagens via upload diretamente no notebook
from google.colab import files
import numpy as np
import matplotlib.pyplot as plt
import os
!pip install rasterio
import rasterio

def carregar_imagens():
    """
    Carrega imagens RGB e NDVI através do botão de upload do Colab.

    Returns:
        Dicionário com as imagens carregadas
    """
    print("Por favor, clique no botão abaixo para fazer upload dos arquivos sorriso_rgb.tif e sorriso_ndvi.tif")

    # Mostra o botão de upload diretamente no notebook
    uploaded = files.upload()

    imagens = {}

    # Processar os arquivos enviados
    for nome_arquivo, conteudo in uploaded.items():
        print(f"Arquivo recebido: {nome_arquivo}")

        # Salvar o arquivo localmente
        with open(nome_arquivo, 'wb') as f:
            f.write(conteudo)

        # Carregar baseado no tipo de arquivo
        try:
            if 'rgb' in nome_arquivo.lower():
                # Carregar imagem RGB
                with rasterio.open(nome_arquivo) as src:
                    rgb_raw = src.read()
                    # Reorganizar para formato de visualização (H, W, C)
                    rgb = np.dstack((rgb_raw[0], rgb_raw[1], rgb_raw[2]))
                    # Normalizar para visualização
                    rgb_norm = np.clip(rgb/255.0, 0, 1)

                    imagens['rgb_raw'] = rgb_raw
                    imagens['rgb'] = rgb_norm
                    print(f"✓ Imagem RGB carregada com sucesso! Formato: {rgb.shape}")

            elif 'ndvi' in nome_arquivo.lower():
                # Carregar imagem NDVI
                with rasterio.open(nome_arquivo) as src:
                    ndvi_raw = src.read(1)
                    imagens['ndvi_raw'] = ndvi_raw
                    print(f"✓ Imagem NDVI carregada com sucesso! Formato: {ndvi_raw.shape}")
            else:
                print(f"Tipo de arquivo não reconhecido: {nome_arquivo}")

        except Exception as e:
            print(f" Erro ao processar {nome_arquivo}: {str(e)}")

    # Verificar se foram carregadas as imagens necessárias
    if 'rgb' in imagens and 'ndvi_raw' in imagens:
        print("\n✓ Todas as imagens necessárias foram carregadas!")
    else:
        print("\n Nem todas as imagens necessárias foram carregadas.")
        print("Imagens disponíveis:", list(imagens.keys()))

    return imagens

# Mostrar uma prévia das imagens
def mostrar_imagens_carregadas(imagens):
    plt.figure(figsize=(15, 6))

    # Mostrar RGB se disponível
    if 'rgb' in imagens:
        plt.subplot(1, 2, 1)
        plt.title("Imagem RGB")
        plt.imshow(imagens['rgb'])
        plt.axis('off')

    # Mostrar NDVI se disponível
    if 'ndvi_raw' in imagens:
        plt.subplot(1, 2, 2)
        plt.title("NDVI")
        plt.imshow(imagens['ndvi_raw'], cmap='RdYlGn')
        plt.colorbar(label='NDVI')
        plt.axis('off')

    plt.tight_layout()
    plt.show()

# Executar a função
imagens = carregar_imagens()

# Mostrar visualização das imagens
if len(imagens) > 0:
    mostrar_imagens_carregadas(imagens)

# Visualizar as imagens
plt.figure(figsize=(15, 10))
plt.subplot(1, 2, 1)
plt.title('Imagem RGB')
plt.imshow(imagens['rgb'])
plt.axis('off')
plt.subplot(1, 2, 2)
plt.title('Imagem NDVI')
plt.imshow(imagens['ndvi_raw'], cmap='RdYlGn')
plt.colorbar(label='NDVI')
plt.axis('off')
plt.tight_layout()
plt.show()

# Imprimir algumas informações sobre as imagens
print(f"Dimensões da imagem RGB: {imagens['rgb'].shape}") # Access rgb from the imagens dictionary
print(f"Dimensões da imagem NDVI: {imagens['ndvi_raw'].shape}") # Access ndvi_raw from the imagens dictionary
print(f"Valor mínimo NDVI: {np.min(imagens['ndvi_raw'])}, Valor máximo NDVI: {np.max(imagens['ndvi_raw'])}") # Access ndvi_raw from the imagens dictionary

# Segmentação baseada em limiar de NDVI
print("\n1. Aplicando segmentação por limiar de NDVI...")

# Definir limiares para diferentes classes de vegetação
ndvi_thresholds = {
    'água': -1.0,
    'solo_nu': 0.2,
    'veg_esparsa': 0.4,
    'veg_densa': 0.6
}

ndvi_raw = imagens['ndvi_raw']

# Criar mapa de segmentação baseado em NDVI
ndvi_segments = np.zeros_like(ndvi_raw, dtype=np.uint8)
ndvi_segments[(ndvi_raw > ndvi_thresholds['água']) & (ndvi_raw <= ndvi_thresholds['solo_nu'])] = 1 # Solo nu
ndvi_segments[(ndvi_raw > ndvi_thresholds['solo_nu']) & (ndvi_raw <= ndvi_thresholds['veg_esparsa'])] = 2 # Vegetação esparsa
ndvi_segments[(ndvi_raw > ndvi_thresholds['veg_esparsa']) & (ndvi_raw <= ndvi_thresholds['veg_densa'])] = 3 # Vegetação moderada
ndvi_segments[ndvi_raw > ndvi_thresholds['veg_densa']] = 4 # Vegetação densa

# Visualizar segmentação por NDVI
plt.figure(figsize=(15, 10))
plt.subplot(1, 2, 1)
plt.title('Imagem NDVI Original')
plt.imshow(ndvi_raw, cmap='RdYlGn')
plt.colorbar(label='NDVI')
plt.axis('off')
plt.subplot(1, 2, 2)
plt.title('Segmentação por Limiares de NDVI')
cmap = plt.cm.get_cmap('viridis', 5) # 5 classes (incluindo 0)
im = plt.imshow(ndvi_segments, cmap=cmap)
cbar = plt.colorbar(im, ticks=[0, 1, 2, 3, 4])
cbar.set_ticklabels(['Sem dados', 'Solo nu', 'Vegetação esparsa', 'Vegetação moderada', 'Vegetação densa'])
plt.axis('off')
plt.tight_layout()
plt.show()

# Salvar como GeoTIFF
from osgeo import gdal
driver = gdal.GetDriverByName('GTiff')
output_path = os.path.join('dados_processados', 'ndvi_segments.tif')
output_raster = driver.Create(output_path, ndvi_segments.shape[1], ndvi_segments.shape[0], 1, gdal.GDT_Byte)

# Verificar se o raster foi criado com sucesso
if output_raster is not None:
    output_raster.GetRasterBand(1).WriteArray(ndvi_segments)
    output_raster = None # Fechando o arquivo
    print(f"Segmentação NDVI salva como GeoTIFF em: {output_path}")
else:
    print("Erro ao criar o arquivo GeoTIFF. Verifique o caminho e as permissões.")

# Também salvar a imagem NDVI original
ndvi_path = os.path.join('dados_processados', 'ndvi_raw.tif')
ndvi_raster = driver.Create(ndvi_path, ndvi_raw.shape[1], ndvi_raw.shape[0], 1, gdal.GDT_Float32)
if ndvi_raster is not None:
    ndvi_raster.GetRasterBand(1).WriteArray(ndvi_raw)
    ndvi_raster = None
    print(f"Imagem NDVI raw salva em: {ndvi_path}")

# Segmentação por clustering (K-MEANS)
print("\n2. Aplicando segmentação por K-means...")

# Importar bibliotecas necessárias
from sklearn.cluster import KMeans
import numpy as np
import matplotlib.pyplot as plt
import os
from osgeo import gdal

# Função para carregar as imagens do Colab
def carregar_imagens():
    """
    Carrega as imagens RGB e NDVI armazenadas no ambiente Colab.
    """
    imagens = {}
    try:
        # Carregar NDVI
        ndvi_path = '/content/sorriso_ndvi.tif'
        if os.path.exists(ndvi_path):
            ndvi_ds = gdal.Open(ndvi_path)
            if ndvi_ds:
                imagens['ndvi_raw'] = ndvi_ds.GetRasterBand(1).ReadAsArray()
                print("NDVI carregado com sucesso.")
            else:
                print(f"Erro ao abrir arquivo NDVI: {ndvi_path}")
        else:
            print(f"Arquivo NDVI não encontrado: {ndvi_path}")

        # Carregar RGB (assumindo que existe um arquivo TIF RGB)
        rgb_path = '/content/sorriso_rgb.tif'
        if os.path.exists(rgb_path):
            rgb_ds = gdal.Open(rgb_path)
            if rgb_ds:
                # Lê as 3 bandas RGB
                r = rgb_ds.GetRasterBand(1).ReadAsArray()
                g = rgb_ds.GetRasterBand(2).ReadAsArray()
                b = rgb_ds.GetRasterBand(3).ReadAsArray()
                # Combina em um array 3D
                imagens['rgb'] = np.dstack((r, g, b))
                print("RGB carregado com sucesso.")
            else:
                print(f"Erro ao abrir arquivo RGB: {rgb_path}")
        else:
            print(f"Arquivo RGB não encontrado: {rgb_path}")

    except Exception as e:
        print(f"Erro ao carregar imagens: {e}")

    return imagens

# Carregar imagens
imagens = carregar_imagens()
rgb = imagens.get('rgb')
ndvi_raw = imagens.get('ndvi_raw')

# Verificar se as imagens foram carregadas corretamente
if rgb is None or ndvi_raw is None:
    print("Erro: As imagens RGB e/ou NDVI não foram carregadas corretamente.")
else:
    # Preparar dados para clustering
    print("Preparando dados para clustering...")

    # Verificar e ajustar as dimensões se necessário
    if rgb.shape[0] != ndvi_raw.shape[0] or rgb.shape[1] != ndvi_raw.shape[1]:
        print(f"Aviso: RGB e NDVI têm dimensões diferentes. RGB: {rgb.shape}, NDVI: {ndvi_raw.shape}")
        # Aqui você poderia adicionar código para redimensionar as imagens

    # Reshape para formato (pixels, features)
    rgb_reshaped = rgb.reshape(-1, 3)  # converte para (n_pixels, 3)
    ndvi_reshaped = ndvi_raw.reshape(-1, 1)  # converte para (n_pixels, 1)

    # Combinar RGB e NDVI em um único array de features
    X = np.hstack((rgb_reshaped, ndvi_reshaped))  # (n_pixels, 4)

    # Remover NaN ou valores inválidos
    mask = ~np.isnan(X).any(axis=1)
    X_valid = X[mask]

    # Aplicar K-means
    k = 5  # Número de clusters
    print(f"Aplicando K-means com {k} clusters em {X_valid.shape[0]} pixels válidos...")
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(X_valid)

    # Reconstruir imagem de segmentação
    segmentation = np.zeros(X.shape[0], dtype=np.uint8)
    segmentation[mask] = labels + 1  # +1 para evitar 0
    segmentation = segmentation.reshape(rgb.shape[0], rgb.shape[1])

    # Visualizar resultados
    plt.figure(figsize=(15, 10))
    plt.subplot(1, 2, 1)
    plt.title('Imagem RGB Original')
    plt.imshow(rgb)
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.title('Segmentação K-means (5 clusters)')
    cmap = plt.cm.get_cmap('tab10', k+1)  # +1 para incluir 0 (sem dados)
    im = plt.imshow(segmentation, cmap=cmap)
    plt.colorbar(im, ticks=range(k+1))
    plt.axis('off')
    plt.tight_layout()
    plt.show()

    # Criar pasta para salvar resultados
    os.makedirs('dados_processados', exist_ok=True)

    # Salvar segmentação como GeoTIFF
    output_path = os.path.join('dados_processados', 'kmeans_segments.tif')
    driver = gdal.GetDriverByName('GTiff')
    output_raster = driver.Create(output_path, segmentation.shape[1], segmentation.shape[0], 1, gdal.GDT_Byte)

    if output_raster is not None:
        output_raster.GetRasterBand(1).WriteArray(segmentation)
        # Se você tiver georreferência do arquivo de entrada, pode copiar:
        # output_raster.SetGeoTransform(input_ds.GetGeoTransform())
        # output_raster.SetProjection(input_ds.GetProjection())
        output_raster = None  # Fechando o arquivo
        print(f"Segmentação K-means salva como GeoTIFF em: {output_path}")
    else:
        print("Erro ao criar o arquivo GeoTIFF. Verifique o caminho e as permissões.")

    # Salvar centróides
    centroids_path = os.path.join('dados_processados', 'kmeans_centroids.npy')
    np.save(centroids_path, kmeans.cluster_centers_)
    print(f"Centróides do K-means salvos em: {centroids_path}")

# Segmentação de Watershed (baseada em gradientes)
print("\n3. Aplicando segmentação Watershed...")

# Importar bibliotecas necessárias
import numpy as np
import matplotlib.pyplot as plt
import os
from osgeo import gdal
from skimage import filters
from skimage.segmentation import watershed
from skimage.color import label2rgb

# Reutilizar a mesma função para carregar imagens
def carregar_imagens():
    """
    Carrega as imagens RGB e NDVI armazenadas no ambiente Colab.
    """
    imagens = {}
    try:
        # Carregar NDVI
        ndvi_path = '/content/sorriso_ndvi.tif'
        if os.path.exists(ndvi_path):
            ndvi_ds = gdal.Open(ndvi_path)
            if ndvi_ds:
                imagens['ndvi_raw'] = ndvi_ds.GetRasterBand(1).ReadAsArray()
                print("NDVI carregado com sucesso.")
            else:
                print(f"Erro ao abrir arquivo NDVI: {ndvi_path}")
        else:
            print(f"Arquivo NDVI não encontrado: {ndvi_path}")

        # Carregar RGB
        rgb_path = '/content/sorriso_rgb.tif'
        if os.path.exists(rgb_path):
            rgb_ds = gdal.Open(rgb_path)
            if rgb_ds:
                # Lê as 3 bandas RGB
                r = rgb_ds.GetRasterBand(1).ReadAsArray()
                g = rgb_ds.GetRasterBand(2).ReadAsArray()
                b = rgb_ds.GetRasterBand(3).ReadAsArray()
                # Combina em um array 3D
                imagens['rgb'] = np.dstack((r, g, b))
                print("RGB carregado com sucesso.")
            else:
                print(f"Erro ao abrir arquivo RGB: {rgb_path}")
        else:
            print(f"Arquivo RGB não encontrado: {rgb_path}")

    except Exception as e:
        print(f"Erro ao carregar imagens: {e}")

    return imagens

# Carregar imagens se ainda não estiverem carregadas
try:
    # Verificar se as variáveis já existem
    rgb.shape
    ndvi_raw.shape
    print("Imagens já carregadas, usando-as diretamente.")
except NameError:
    # Se as variáveis não existirem, carregar as imagens
    print("Carregando imagens...")
    imagens = carregar_imagens()
    rgb = imagens.get('rgb')
    ndvi_raw = imagens.get('ndvi_raw')

# Verificar se as imagens foram carregadas corretamente
if rgb is None or ndvi_raw is None:
    print("Erro: As imagens RGB e/ou NDVI não foram carregadas corretamente.")
else:
    # Preparar dados para segmentação Watershed
    print("Preparando dados para segmentação Watershed...")

    # Verificar e ajustar as dimensões se necessário
    if rgb.shape[0] != ndvi_raw.shape[0] or rgb.shape[1] != ndvi_raw.shape[1]:
        print(f"Aviso: RGB e NDVI têm dimensões diferentes. RGB: {rgb.shape}, NDVI: {ndvi_raw.shape}")
        # Aqui você poderia adicionar código para redimensionar as imagens

    # Normalizar o NDVI caso não esteja no intervalo [0,1]
    # Muitas funções de processamento de imagem esperam valores entre 0 e 1
    ndvi_norm = ndvi_raw.copy()
    if np.nanmin(ndvi_raw) < 0 or np.nanmax(ndvi_raw) > 1:
        print("Normalizando NDVI para o intervalo [0,1] para cálculo do gradiente...")
        ndvi_min = np.nanmin(ndvi_raw)
        ndvi_max = np.nanmax(ndvi_raw)
        ndvi_norm = (ndvi_raw - ndvi_min) / (ndvi_max - ndvi_min)

    # Criar uma imagem de gradiente a partir do NDVI normalizado
    print("Calculando gradientes com filtro Sobel...")
    edges = filters.sobel(ndvi_norm)

    # Definir marcadores para watershed
    markers = np.zeros_like(ndvi_raw, dtype=np.int32)

    # Definir marcadores baseados em NDVI
    print("Definindo marcadores para segmentação...")
    markers[ndvi_raw < 0.2] = 1  # Baixo NDVI (solo nu, água)
    markers[ndvi_raw > 0.6] = 2  # Alto NDVI (vegetação densa)

    # Aplicar watershed
    print("Aplicando segmentação Watershed...")
    watershed_segments = watershed(edges, markers)

    # Visualizar segmentação watershed
    plt.figure(figsize=(15, 10))
    plt.subplot(1, 2, 1)
    plt.title('Imagem de Bordas (Gradientes)')
    plt.imshow(edges, cmap='gray')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.title('Segmentação Watershed')
    overlay = label2rgb(watershed_segments, image=rgb, bg_label=0)
    plt.imshow(overlay)
    plt.axis('off')
    plt.tight_layout()
    plt.show()

    # Criar pasta para salvar resultados
    os.makedirs('dados_processados', exist_ok=True)

    # Salvar segmentação como GeoTIFF
    output_path = os.path.join('dados_processados', 'watershed_segments.tif')
    driver = gdal.GetDriverByName('GTiff')
    output_raster = driver.Create(output_path, watershed_segments.shape[1],
                                watershed_segments.shape[0], 1, gdal.GDT_Byte)

    if output_raster is not None:
        output_raster.GetRasterBand(1).WriteArray(watershed_segments)
        # Se você tiver georreferência do arquivo de entrada, pode copiar:
        # ndvi_ds = gdal.Open('/content/sorriso_ndvi.tif')
        # if ndvi_ds:
        #     output_raster.SetGeoTransform(ndvi_ds.GetGeoTransform())
        #     output_raster.SetProjection(ndvi_ds.GetProjection())
        output_raster = None  # Fechando o arquivo
        print(f"Segmentação Watershed salva como GeoTIFF em: {output_path}")
    else:
        print("Erro ao criar o arquivo GeoTIFF. Verifique o caminho e as permissões.")

    # Salvar também a imagem de gradientes para referência
    gradient_path = os.path.join('dados_processados', 'watershed_gradients.tif')
    gradient_raster = driver.Create(gradient_path, edges.shape[1], edges.shape[0], 1, gdal.GDT_Float32)

    if gradient_raster is not None:
        gradient_raster.GetRasterBand(1).WriteArray(edges)
        gradient_raster = None
        print(f"Imagem de gradientes salva em: {gradient_path}")



# Instalar bibliotecas necessárias
!pip install gdal rasterio matplotlib numpy pandas scikit-learn


import os
import numpy as np
import matplotlib.pyplot as plt
from time import time
import rasterio
from rasterio.plot import show
import pandas as pd

# Função de carregamento usando rasterio em vez de gdal
def carregar_dados():
    dados = {}
    # Defina os caminhos para seus arquivos no Colab
    caminhos = {
        'ndvi': '/content/sorriso_ndvi.tif',
        'kmeans': '/content/dados_processados/kmeans_segments.tif',
        'watershed': '/content/dados_processados/watershed_segments.tif',
        'rgb': '/content/sorriso_rgb.tif'
    }

    # Carrega cada arquivo
    for nome, caminho in caminhos.items():
        if os.path.exists(caminho):
            try:
                with rasterio.open(caminho) as src:
                    if nome == 'rgb':
                        # Para imagens RGB (3 bandas)
                        bandas = []
                        for i in range(1, src.count + 1):
                            bandas.append(src.read(i))
                        dados[nome] = np.dstack(bandas)
                    else:
                        # Para imagens de uma banda
                        dados[nome] = src.read(1)
                    print(f"✓ Arquivo '{nome}' carregado: {dados[nome].shape}")
            except Exception as e:
                print(f"✗ Erro ao carregar {nome}: {str(e)}")
        else:
            print(f"✗ Arquivo não encontrado: {caminho}")

    return dados

# Função para salvar um array NumPy como um arquivo TIFF
def salvar_segmentacao(data, caminho_arquivo, crs=None, transform=None):
    """Salva um array NumPy como um arquivo TIFF de uma banda."""
    if data is not None:
        altura, largura = data.shape
        with rasterio.open(
            caminho_arquivo,
            'w',
            driver='GTiff',
            height=altura,
            width=largura,
            count=1,
            dtype=data.dtype,
            crs=crs,
            transform=transform,
        ) as dst:
            dst.write(data, 1)
        print(f"✓ Segmentação salva em: {'/content/resultados/graficos'}")
    else:
        print(f"✗ Nenhum dado para salvar em: {'/content/resultados/graficos'}")

# Teste da função
def validar_carregamento():
    print("Iniciando carregamento dos dados...")
    inicio = time()
    dados = carregar_dados()
    fim = time()
    print(f"Tempo de carregamento: {fim - inicio:.2f} segundos\n")

    # Verificar quais dados foram carregados
    print(f"Dados carregados: {list(dados.keys())}")

    # Se nenhum dado foi carregado, sugerir verificação de caminhos
    if not dados:
        print("\nNENHUM DADO CARREGADO! Verifique:")
        print("1. Se os arquivos existem nos caminhos especificados")
        print("2. Use o comando abaixo para listar os arquivos disponíveis:")
        print("    !ls -la /content/")
        print("    !ls -la /content/dados_processados/")
        return dados

    # Validar cada tipo de dado carregado e salvar as segmentações
    if 'ndvi' in dados:
        print("\n=== NDVI ===")
        ndvi = dados['ndvi']
        print(f"Shape: {ndvi.shape}")
        print(f"Valores - Min: {np.nanmin(ndvi):.4f}, Max: {np.nanmax(ndvi):.4f}, Média: {np.nanmean(ndvi):.4f}")

        # Visualizar NDVI
        plt.figure(figsize=(8, 8))
        plt.imshow(ndvi, cmap='RdYlGn')
        plt.colorbar(label='NDVI')
        plt.title('NDVI')
        plt.show()


    if 'kmeans' in dados:
        print("\n=== K-means ===")
        kmeans = dados['kmeans']
        print(f"Shape: {kmeans.shape}")
        n_clusters = len(np.unique(kmeans))
        print(f"Número de clusters: {n_clusters}")

        # Visualizar K-means
        plt.figure(figsize=(8, 8))
        plt.imshow(kmeans, cmap='tab20')
        plt.colorbar(label='Cluster')
        plt.title('Segmentação K-means')
        plt.show()

        # Salvar segmentação K-means
        caminho_salvar_kmeans = '/content/dados_processados/kmeans_segments_salvo.tif'
        # Para salvar corretamente, você precisaria das informações de CRS e Transform do arquivo original
        # Vamos tentar abrir o arquivo original para obter essas informações
        try:
            with rasterio.open('/content/dados_processados/kmeans_segments.tif') as src_info:
                crs_kmeans = src_info.crs
                transform_kmeans = src_info.transform
                salvar_segmentacao(kmeans, caminho_salvar_kmeans, crs=crs_kmeans, transform=transform_kmeans)
        except Exception as e:
            print(f"✗ Erro ao obter informações de CRS/Transform para K-means: {e}")
            salvar_segmentacao(kmeans, caminho_salvar_kmeans) # Salva sem informações geográficas

    if 'watershed' in dados:
        print("\n=== Watershed ===")
        watershed = dados['watershed']
        print(f"Shape: {watershed.shape}")
        n_segmentos = len(np.unique(watershed)) - (1 if -1 in np.unique(watershed) else 0)
        print(f"Número de segmentos: {n_segmentos}")

        # Visualizar Watershed
        plt.figure(figsize=(8, 8))
        plt.imshow(watershed, cmap='nipy_spectral')
        plt.colorbar(label='Segmento')
        plt.title('Segmentação Watershed')
        plt.show()

        # Salvar segmentação Watershed
        caminho_salvar_watershed = '/content/dados_processados/watershed_segments_salvo.tif'
        # Para salvar corretamente, você precisaria das informações de CRS e Transform do arquivo original
        # Vamos tentar abrir o arquivo original para obter essas informações
        try:
            with rasterio.open('/content/dados_processados/watershed_segments.tif') as src_info:
                crs_watershed = src_info.crs
                transform_watershed = src_info.transform
                salvar_segmentacao(watershed, caminho_salvar_watershed, crs=crs_watershed, transform=transform_watershed)
        except Exception as e:
            print(f"✗ Erro ao obter informações de CRS/Transform para Watershed: {e}")
            salvar_segmentacao(watershed, caminho_salvar_watershed) # Salva sem informações geográficas

    if 'rgb' in dados:
        print("\n=== RGB ===")
        rgb = dados['rgb']
        print(f"Shape: {rgb.shape}")

        # Normalizar RGB para visualização
        rgb_norm = np.copy(rgb).astype(np.float32)
        for i in range(3):
            banda = rgb_norm[:,:,i]
            if np.all(banda == 0):
                continue
            min_val = np.percentile(banda[banda > 0], 2)
            max_val = np.percentile(banda[banda > 0], 98)
            if max_val > min_val:
                rgb_norm[:,:,i] = np.clip((banda - min_val) / (max_val - min_val), 0, 1)

        # Visualizar RGB
        plt.figure(figsize=(8, 8))
        plt.imshow(rgb_norm)
        plt.title('Imagem RGB')
        plt.show()

    return dados

# Verificar os arquivos disponíveis no Colab
print("Arquivos disponíveis em /content/:")
!ls -la /content/

# Verificar se o diretório de dados processados existe
!mkdir -p /content/dados_processados/
print("\nArquivos disponíveis em /content/dados_processados/:")
!ls -la /content/dados_processados/

# Executar a validação (que agora inclui salvar as segmentações)
dados = validar_carregamento()
print("\nValidação e salvamento concluídos!")

"""# Etapa 3 – Construção do Modelo de IA 🤖

*   Selecionar um modelo de aprendizado de máquina ou redes neurais para previsão da produtividade.
*   Treinar o modelo utilizando os dados históricos e validar sua capacidade preditiva.
*   Ajustar hiperparâmetros e otimizar o desempenho do modelo.





"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import joblib
import os
import rasterio
from skimage.feature import graycomatrix, graycoprops

# 1. Carregar os dados
file_path = os.path.join('dados_processados', 'base.csv')
base = pd.read_csv(file_path)

# 2. Carregar imagens NDVI e extrair características
def extrair_textura(caminho_imagem): # Usar 'caminho_imagem' como argumento
    # Carregar a imagem NDVI usando o caminho fornecido
    with rasterio.open(caminho_imagem) as src:
        ndvi_image = src.read(1)

    # Calcular a matriz GLCM
    glcm = graycomatrix(ndvi_image, distances=[1], angles=[0], levels=256, symmetric=True, normed=True)

    # Extrair características de textura
    textura = {
        'contraste': graycoprops(glcm, 'contrast')[0, 0],
        'dissimilaridade': graycoprops(glcm, 'dissimilarity')[0, 0],
        'homogeneidade': graycoprops(glcm, 'homogeneity')[0, 0],
        # ... (outras propriedades de textura) ...
    }
    return textura #Fixed: Indentation corrected here

# Chamar a função extrair_textura com o caminho da imagem
caminho_ndvi = '/content/sorriso_ndvi.tif'
textura_features = extrair_textura(caminho_ndvi)



# Carregar a imagem NDVI completa
with rasterio.open('/content/sorriso_ndvi.tif') as src:
    ndvi_image = src.read(1)

# Extrair características de textura da imagem completa
textura_features = extrair_textura(ndvi_image)

# Atribuir as características de textura a todas as linhas do DataFrame
# (considerando que as características são as mesmas para todos os anos)
for feature, value in textura_features.items():
    base[feature] = value

# 3. Seleção de características (incluindo features das imagens)
features = ['ndvi_medio_ano', 'temp_media_ciclo', 'rad_media_ciclo', 'contraste', 'dissimilaridade', 'homogeneidade']  # Adicione as features de textura
target = 'produtividade'

# 4. Preparar os dados para treinamento
X = base[features]
y = base[target]

# 5. Dividir os dados em conjuntos de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 6. Criar e treinar o modelo (Random Forest)
model = RandomForestRegressor(random_state=42)

# 7. Ajustar hiperparâmetros com GridSearchCV
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
}
grid_search = GridSearchCV(model, param_grid, cv=5, scoring='neg_mean_squared_error')
grid_search.fit(X_train, y_train)

# 8. Obter o melhor modelo e avaliar
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Erro Quadrático Médio: {mse}")
print(f"R-quadrado: {r2}")
print(f"Melhores Hiperparâmetros: {grid_search.best_params_}")

# 9. Salvar o melhor modelo
model_path = os.path.join('resultados', 'modelos', 'modelo_produtividade_com_imagens.joblib')
joblib.dump(best_model, model_path)
print(f"Modelo treinado salvo em: {model_path}")